### ISSUE TITLE
add a check to validate that default.aspx/default.aspx.cs have not been altered

### ISSUE THREAD

**Issue by cathalconnolly** [DNNCommunity/SecurityAnalyzer#10]
we should add a check to hash the contents of default.aspx/default.aspx.cs and flag if the page(s) have been altered - this would help alert users in the case that their page had additional tags (e.g. for SEO spam links) added.

**Comment by sleupold** [comment]
I know a couple of client sites, where the owner modified default.aspx on purpose. If we use a hash value to compare, the owner needs an option to update the hash value after install and modification.

**Comment by WillStrohl** [comment]
I disagree with Sebastian. A core code change is not only a worst practice (even when it's seemingly only way to get something done), but a core code change should also be considered a potential security risk.  I think a check for the default.aspx hash is a good thing.

**Comment by WillStrohl** [comment]
To be clear, like with people who choose to keep an old password and ignore the message in this module, they can do the same with the Default.aspx hash if they choose to modify it themselves.

**Comment by CaveDeb** [comment]
Due to the recent critical patch, I have run the security analyzer on dozens of sites, and there is a consistent issue I have noticed. Fresh install DNN 9 sites don't flag the default page, but all sites upgraded to DNN 8 or DNN 9 from earlier DNN 7 versions do flag it, consistently. Another difference between the upgraded sites and the fresh installs: upgraded sites have two default files: Default.aspx, and Default.aspx.cs. Fresh DNN 9 installs that have not been upgraded from earlier versions have the Default.aspx file, but not the Default.aspx.cs file. 

I have on several flagged sites opened up these files and cannot find anything suspicious in them. Is this simply flagged because the current DNN 9 version doesn't expect to see the aspx.cs file? Is it still necessary?

**Comment by sleupold** [comment]
DNN 9 website is precompiled, i.e. .cs files are no longer needed and should be removed.
Note: this does not apply to 3rd party extensions installed. You should be able to identify old .cs files after upgrading to DNN 9 by date.

**Comment by CaveDeb** [comment]
Thanks! I have safely removed the aspx.cs file from one of my DNN 9 sites. However, this still doesn't correct the default page flag. It's also worth noting that whether or not it's flagged depends on how the security analyzer is reached:
![security-analyzer-default-page-comparison](https://user-images.githubusercontent.com/17413119/27802081-2f2e3894-5fe7-11e7-9575-9a8e3119caa1.jpg)
This image includes two screen shots from the same site's security analyzers. The top one shows a pass when the security analyzer is reached through the settings tab on the persona bar, whereas the lower one fails it when accessed through the manage tab. Thoughts?

**Comment by valadas** [comment]
I think this was resolved so I am closing this issue, if it is not the case, please open a new issue on this repository https://github.com/dnnsoftware/Dnn.AdminExperience which has the new security analyser
