### ISSUE TITLE
Mark State of Default.aspx as "Okay"

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/SecurityAnalyzer#16]
There should be a feature that allows a superuser to mark the state of the Default.aspx.  

For example, if an admin has done the unthinkable and made core changes to the Default.aspx, it will be flagged here.  However, it would be ideal if the admin could review the page and come back to the module and say the change is okay, essentially putting a virtual "checkmark" on the state of the page (and maybe even saving it).  

This would allow the admin to come back here and see when and if the page has changed again without their knowledge knowledge.  

The current implementation will require the admin to check the page every single time they run the scan, or something worse... one might just get used to seeing it and ignore the error/warning altogether.

**Comment by valadas** [comment]
I am closing this since a similar issue discussion indicated that
1. modifying the core files is bad practice to begin with.
2. the file will get replaced on each upgrade and the releases come faster now.
3. if the file is modified and we allow marking it safe without knowing what is there, it can provide a false sense of security.

If you disagree with this and want to discuss it further, please open an issue in the new Security Analyzer at https://github.com/dnnsoftware/Dnn.AdminExperience
