### ISSUE TITLE
Writing Telerik.Web.UI.DialogParametersEncryptionKey key to web.config with encrypted appsettings

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/SecurityAnalyzer#29]
All my installs of version 8.1.1 went fine but the one where the sysop encrypted the appsettings (not our own server).
The module still injected the Telerik.Web.UI.DialogParametersEncryptionKey to the appsettings in  web.config which crashed the site with a config error.
Might be good to check in advance if the section is encrypted

**Comment by bdukes** [comment]
Ideally, this is an exception thrown from [`Config.AddAppSetting`](https://github.com/dnnsoftware/Dnn.Platform/blob/2ca8499872eacccb31cb453385cadadbca212a75/DNN%20Platform/Library/Common/Utilities/Config.cs#L76-L111), the DNN Platform API that the Security Analyzer is calling, but since a change there would only help newer versions of DNN, this module should also check for this problem.

**Comment by galatrash** [comment]
There is a newer released version of SA which might have this fixed.

**Comment by bdukes** [comment]
We just encountered this with the latest release version

**Comment by galatrash** [comment]
I've created an issue [here](https://dnntracker.atlassian.net/browse/DNN-10276) to have this fixed.

**Comment by valadas** [comment]
Closing as per last comment
